#!/bin/bash

DIR="../../runs"  # The parent directory of runs
SUB="INCAR"  # The submit file
SUBMITTER="lmp_serial"  # The scheduler submit command

FNAME=find ${DIR} -type f -name ${SUB}

# Submit all submission files in DIR
cd ${DIR}
IFS=$'\n'
while read -r FNAME ;
do
    pushd $(dirname "${FNAME}") > /dev/null
    ${SUBMITTER} < ${SUB}
    popd > /dev/null
done < <(find . -type f -name ${SUB})
