#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[10.53706398, 10.81632644, 11.0955889, 11.37485136, 11.65411382]"  # List of cubic lattice constants
ELEMENTS="['Zr', 'Cu']"  # Elements
NUMBERS="[50, 50]"  # Number corresponding to each element
SAVE="'../../runs/Zr50Cu50/2000K'"  # Location to save POSCAR
INCAR="'../templates/input/Zr50Cu50_temperature_2000K'"  # The VASP input file
POTCAR="'../templates/potential/ZrCu.lammps.eam'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${SAVE}" "${RUNS}" "${INCAR}" "${POTCAR}" "${SUB}"
